//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VfpToSqlBulkCopy.Logging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDetail
    {
        public int Id { get; set; }
        public System.DateTime Begin { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Exception { get; set; }
        public int UploadHeaderId { get; set; }
    
        public virtual UploadHeader UploadHeader { get; set; }
    }
}
