USE [master]
GO
/****** Object:  Database [UploadLogging]    Script Date: 4/3/2018 9:06:14 PM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'UploadLogging')
BEGIN
CREATE DATABASE [UploadLogging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UploadLogging', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\UploadLogging.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UploadLogging_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\UploadLogging_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
END

GO
ALTER DATABASE [UploadLogging] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UploadLogging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UploadLogging] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UploadLogging] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UploadLogging] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UploadLogging] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UploadLogging] SET ARITHABORT OFF 
GO
ALTER DATABASE [UploadLogging] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UploadLogging] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UploadLogging] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UploadLogging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UploadLogging] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UploadLogging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UploadLogging] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UploadLogging] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UploadLogging] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UploadLogging] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UploadLogging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UploadLogging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UploadLogging] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UploadLogging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UploadLogging] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UploadLogging] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UploadLogging] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UploadLogging] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UploadLogging] SET  MULTI_USER 
GO
ALTER DATABASE [UploadLogging] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UploadLogging] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UploadLogging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UploadLogging] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [UploadLogging] SET DELAYED_DURABILITY = DISABLED 
GO
USE [UploadLogging]
GO
/****** Object:  Table [dbo].[UploadDetail]    Script Date: 4/3/2018 9:06:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UploadDetail]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[UploadDetail](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Begin] [datetime] NOT NULL,
	[End] [datetime] NULL,
	[Exception] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UploadHeaderId] [int] NOT NULL,
 CONSTRAINT [PK_UploadDetail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[UploadHeader]    Script Date: 4/3/2018 9:06:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UploadHeader]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[UploadHeader](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Begin] [datetime] NOT NULL,
	[End] [datetime] NULL,
 CONSTRAINT [PK_UploadHeader] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_UploadDetail_Begin]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[UploadDetail] ADD  CONSTRAINT [DF_UploadDetail_Begin]  DEFAULT (getdate()) FOR [Begin]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_UploadHeader_Begin]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[UploadHeader] ADD  CONSTRAINT [DF_UploadHeader_Begin]  DEFAULT (getdate()) FOR [Begin]
END

GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_UploadDetail_UploadHeader]') AND parent_object_id = OBJECT_ID(N'[dbo].[UploadDetail]'))
ALTER TABLE [dbo].[UploadDetail]  WITH CHECK ADD  CONSTRAINT [FK_UploadDetail_UploadHeader] FOREIGN KEY([UploadHeaderId])
REFERENCES [dbo].[UploadHeader] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_UploadDetail_UploadHeader]') AND parent_object_id = OBJECT_ID(N'[dbo].[UploadDetail]'))
ALTER TABLE [dbo].[UploadDetail] CHECK CONSTRAINT [FK_UploadDetail_UploadHeader]
GO
USE [master]
GO
ALTER DATABASE [UploadLogging] SET  READ_WRITE 
GO
